# Generated by Claude Code
# ML/stacking/__init__.py
# Stacking ensemble meta-learner package for the fake news classifier.
# Pipeline:
#   1. generate_predictions.py  — generate train/val base model predictions
#   2. data.py                  — load, merge, normalise, return DataLoaders
#   3. mlp.py                   — MLP meta-learner architecture
#   4. train.py                 — training loop with early stopping
#   5. evaluate.py              — test evaluation and comparison table
