# Generated by Claude Code
# ML/stacking/data.py
#
# Loads and merges base-model prediction CSVs, computes disagreement features,
# normalises probability columns, and returns PyTorch DataLoaders.
#
# Assumptions / column mapping:
#   - Each prediction CSV (gru/lstm/nb_{split}_preds.csv) has columns:
#       row_id, true_label ("fake"|"real"), pred_label, prob_fake
#   - Feature vector fed to the MLP (5 features):
#       [gru_prob, lstm_prob, nb_prob, prob_std, prob_spread]
#       prob_std    = std  of the 3 base probabilities (disagreement)
#       prob_spread = max - min of the 3 base probabilities (range)
#   - MinMaxScaler is fit on the train split and applied to val/test.
#     Justification: probabilities are already in [0, 1]; MinMaxScaler
#     preserves that natural range and prevents negative values entering ReLU.
#   - prob_std and prob_spread are derived from the scaled probabilities so
#     they share the same [0, 1] scale without needing separate normalisation.

import sys
from pathlib import Path

SCRIPT_DIR   = Path(__file__).resolve().parent
ML_DIR       = SCRIPT_DIR.parent
PROJECT_ROOT = ML_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT))

import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import MinMaxScaler

PREDS_DIR = ML_DIR / "artifacts" / "preds"


def load_split(
    split: str,
    scaler: MinMaxScaler = None,
    fit_scaler: bool = False,
):
    """
    Load and merge prediction CSVs for a given split.

    Parameters
    ----------
    split      : 'train' | 'val' | 'test'
    scaler     : pre-fitted MinMaxScaler (pass None when fit_scaler=True)
    fit_scaler : if True, fit the scaler on this split's probability columns

    Returns
    -------
    X      : FloatTensor shape (N, 5)
             [gru_prob, lstm_prob, nb_prob, prob_std, prob_spread]
    y      : FloatTensor shape (N,)
    scaler : fitted MinMaxScaler
    """
    gru_df  = pd.read_csv(PREDS_DIR / f"gru_{split}_preds.csv")
    lstm_df = pd.read_csv(PREDS_DIR / f"lstm_{split}_preds.csv")
    nb_df   = pd.read_csv(PREDS_DIR / f"nb_{split}_preds.csv")

    merged = (
        gru_df[["row_id", "true_label", "prob_fake"]]
        .rename(columns={"prob_fake": "gru_prob"})
        .merge(
            lstm_df[["row_id", "prob_fake"]].rename(columns={"prob_fake": "lstm_prob"}),
            on="row_id",
        )
        .merge(
            nb_df[["row_id", "prob_fake"]].rename(columns={"prob_fake": "nb_prob"}),
            on="row_id",
        )
    )

    merged["label"] = (merged["true_label"] == "fake").astype(int)

    # scale the 3 raw probability columns first
    prob_cols = ["gru_prob", "lstm_prob", "nb_prob"]
    if fit_scaler:
        scaler = MinMaxScaler()
        merged[prob_cols] = scaler.fit_transform(merged[prob_cols].to_numpy())
    else:
        merged[prob_cols] = scaler.transform(merged[prob_cols].to_numpy())

    # disagreement features derived from the scaled probs
    probs_mat = merged[prob_cols].to_numpy()
    merged["prob_std"]    = probs_mat.std(axis=1)
    merged["prob_spread"] = probs_mat.max(axis=1) - probs_mat.min(axis=1)

    feature_cols = ["gru_prob", "lstm_prob", "nb_prob", "prob_std", "prob_spread"]
    features = merged[feature_cols].to_numpy(dtype=np.float32)
    labels   = merged["label"].to_numpy(dtype=np.float32)

    return torch.from_numpy(features), torch.from_numpy(labels), scaler


def get_dataloaders(batch_size: int = 64):
    """
    Load all three splits and return DataLoaders.

    Returns
    -------
    train_loader, val_loader, test_loader, scaler
    """
    X_train, y_train, scaler = load_split("train", fit_scaler=True)
    X_val,   y_val,   _      = load_split("val",   scaler=scaler)
    X_test,  y_test,  _      = load_split("test",  scaler=scaler)

    train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=batch_size, shuffle=True)
    val_loader   = DataLoader(TensorDataset(X_val,   y_val),   batch_size=batch_size, shuffle=False)
    test_loader  = DataLoader(TensorDataset(X_test,  y_test),  batch_size=batch_size, shuffle=False)

    return train_loader, val_loader, test_loader, scaler
