# Generated by Claude Code
# ML/stacking/evaluate.py
#
# Loads the best MLP checkpoint and evaluates it on the test split.
# Also computes metrics for each base model using their test prediction CSVs,
# then prints a side-by-side comparison table.
#
# Optimal classification threshold is selected by maximising F1 on the
# validation split, then applied to the test split (no test-set peeking).
#
# Usage (from project root):
#   python ML/stacking/evaluate.py
#
# Prerequisites:
#   1. ML/stacking/generate_predictions.py must have been run.
#   2. ML/stacking/train.py must have produced a checkpoint.

import sys
from pathlib import Path

SCRIPT_DIR   = Path(__file__).resolve().parent
ML_DIR       = SCRIPT_DIR.parent
PROJECT_ROOT = ML_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT))

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
)

from ML.stacking.data import get_dataloaders
from ML.stacking.mlp  import MLPMetaLearner

CHECKPOINT_PATH = SCRIPT_DIR / "checkpoints" / "best_mlp.pt"
PREDS_DIR       = ML_DIR / "artifacts" / "preds"
DEVICE          = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ── MLP inference ─────────────────────────────────────────────────────────────
def run_mlp_on_loader(model: MLPMetaLearner, loader) -> tuple[np.ndarray, np.ndarray]:
    """Return (y_true, y_prob) for any DataLoader."""
    model.eval()
    all_probs, all_true = [], []
    with torch.no_grad():
        for X_batch, y_batch in loader:
            probs = model(X_batch.to(DEVICE)).cpu().numpy()
            all_probs.append(probs)
            all_true.append(y_batch.numpy())
    return np.concatenate(all_true), np.concatenate(all_probs)


# ── optimal threshold ─────────────────────────────────────────────────────────
def find_best_threshold(y_true: np.ndarray, y_prob: np.ndarray) -> float:
    """
    Search thresholds in [0.30, 0.70] and return the one that maximises F1.
    Uses the validation split so the test split is never peeked at.
    """
    best_t, best_f1 = 0.5, 0.0
    for t in np.arange(0.30, 0.71, 0.01):
        f1 = f1_score(y_true, (y_prob >= t).astype(int), zero_division=0)
        if f1 > best_f1:
            best_f1, best_t = f1, t
    return float(best_t)


# ── metric helpers ────────────────────────────────────────────────────────────
def compute_metrics(y_true: np.ndarray, y_prob: np.ndarray, threshold: float = 0.5) -> dict:
    y_pred = (y_prob >= threshold).astype(int)
    return {
        "accuracy":  accuracy_score(y_true, y_pred),
        "precision": precision_score(y_true, y_pred, zero_division=0),
        "recall":    recall_score(y_true, y_pred, zero_division=0),
        "f1":        f1_score(y_true, y_pred, zero_division=0),
        "auc":       roc_auc_score(y_true, y_prob),
    }


# ── base model metrics ────────────────────────────────────────────────────────
def base_model_metrics(model_name: str) -> dict:
    df     = pd.read_csv(PREDS_DIR / f"{model_name}_test_preds.csv")
    y_true = (df["true_label"] == "fake").astype(int).to_numpy()
    y_prob = df["prob_fake"].to_numpy(dtype=float)
    return compute_metrics(y_true, y_prob)


# ── pretty table ──────────────────────────────────────────────────────────────
def print_comparison_table(results: dict):
    header = (
        f"{'Model':<16} | {'Accuracy':>8} | {'Precision':>9} | "
        f"{'Recall':>6} | {'F1':>6} | {'AUC-ROC':>7}"
    )
    sep = "-" * len(header)
    print(sep)
    print(header)
    print(sep)
    for name, m in results.items():
        print(
            f"{name:<16} | {m['accuracy']:>8.4f} | {m['precision']:>9.4f} | "
            f"{m['recall']:>6.4f} | {m['f1']:>6.4f} | {m['auc']:>7.4f}"
        )
    print(sep)


def print_confusion_matrix(y_true: np.ndarray, y_prob: np.ndarray, threshold: float):
    y_pred = (y_prob >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    print("\nMLP Ensemble — Confusion Matrix:")
    print(f"               Predicted Real  Predicted Fake")
    print(f"  Actual Real  {tn:>14,}  {fp:>14,}")
    print(f"  Actual Fake  {fn:>14,}  {tp:>14,}")
    print(f"\n  TN={tn:,}  FP={fp:,}  FN={fn:,}  TP={tp:,}")


# ── entry point ───────────────────────────────────────────────────────────────
def evaluate():
    print("=" * 70)
    print("Stacking Ensemble — Evaluation on Test Split")
    print("=" * 70)

    if not CHECKPOINT_PATH.exists():
        print(f"ERROR: No checkpoint found at {CHECKPOINT_PATH}")
        print("       Run ML/stacking/train.py first.")
        sys.exit(1)

    print("Loading data …")
    _, val_loader, test_loader, _ = get_dataloaders()
    print("Data loaded.\n")

    model = MLPMetaLearner()
    model.load_state_dict(torch.load(CHECKPOINT_PATH, map_location="cpu"))
    model.to(DEVICE)

    # find best threshold on val split (no test peeking)
    y_val_true, y_val_prob = run_mlp_on_loader(model, val_loader)
    threshold = find_best_threshold(y_val_true, y_val_prob)
    val_f1_at_threshold = f1_score(y_val_true, (y_val_prob >= threshold).astype(int))
    print(f"Optimal threshold (val F1={val_f1_at_threshold:.4f}): {threshold:.2f}\n")

    # evaluate on test split with the tuned threshold
    y_true, y_prob_mlp = run_mlp_on_loader(model, test_loader)
    mlp_metrics = compute_metrics(y_true, y_prob_mlp, threshold=threshold)

    results = {
        "GRU":          base_model_metrics("gru"),
        "LSTM":         base_model_metrics("lstm"),
        "Naive Bayes":  base_model_metrics("nb"),
        "MLP Ensemble": mlp_metrics,
    }

    print("=" * 70)
    print(f"Side-by-Side Comparison — Test Split  (MLP threshold={threshold:.2f})")
    print("=" * 70)
    print_comparison_table(results)
    print_confusion_matrix(y_true, y_prob_mlp, threshold)
    print()


if __name__ == "__main__":
    evaluate()
