# Generated by Claude Code
# ML/stacking/export_api_models.py
#
# Copies / exports all model artifacts needed by the API into API/model/.
# Run this once after training the MLP meta-learner.
#
# Prerequisites (must exist before running):
#   ML/stacking/checkpoints/best_mlp.pt    — from train.py
#   ML/stacking/checkpoints/mlp_scaler.pkl — from train.py
#   ML/artifacts/models/lstm_classifier.pt — from base model training
#   ML/artifacts/vocabs/lstm_vocab.json    — from base model training
#   ML/data/WELFake_Dataset.csv            — original dataset
#   ML/data/splits/train_ids.csv           — frozen split
#
# Outputs written to API/model/:
#   lstm_classifier.pt   — LSTM weights
#   lstm_vocab.json      — LSTM vocabulary
#   mlp_best.pt          — MLP meta-learner weights
#   mlp_scaler.pkl       — MinMaxScaler fitted on train probabilities
#   nb_vectorizer.pkl    — CountVectorizer fitted on training text
#   nb_params.npz        — NB log-probability arrays
#
# Usage (from project root):
#   python ML/stacking/export_api_models.py

import sys
import shutil
from pathlib import Path

SCRIPT_DIR   = Path(__file__).resolve().parent
ML_DIR       = SCRIPT_DIR.parent
PROJECT_ROOT = ML_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT))

import pickle
import numpy as np
import pandas as pd

from ML.src.models.BernoulliNaiveBayes import BernoulliNaiveBayes
from ML.src.processing import clean

ARTIFACTS  = ML_DIR / "artifacts"
SPLITS_DIR = ML_DIR / "data" / "splits"
DATASET    = ML_DIR / "data" / "WELFake_Dataset.csv"
CKPT_DIR   = SCRIPT_DIR / "checkpoints"
API_MODEL  = PROJECT_ROOT / "API" / "model"

API_MODEL.mkdir(parents=True, exist_ok=True)


def _copy(src: Path, dst_name: str):
    dst = API_MODEL / dst_name
    shutil.copy2(src, dst)
    print(f"  Copied  {src.name} → {dst}")


def export_lstm():
    print("\n[LSTM] Copying weights and vocab …")
    _copy(ARTIFACTS / "models" / "lstm_classifier.pt", "lstm_classifier.pt")
    _copy(ARTIFACTS / "vocabs"  / "lstm_vocab.json",   "lstm_vocab.json")


def export_mlp():
    print("\n[MLP] Copying checkpoint and scaler …")
    _copy(CKPT_DIR / "best_mlp.pt",    "mlp_best.pt")
    _copy(CKPT_DIR / "mlp_scaler.pkl", "mlp_scaler.pkl")


def export_nb():
    """Fit NB on full training split and save vectorizer + parameter arrays."""
    print("\n[NB] Fitting on full training split …")

    df = pd.read_csv(DATASET).reset_index(drop=True)
    if "row_id" not in df.columns:
        df["row_id"] = np.arange(len(df))
    df = df.set_index("row_id", drop=False)
    df["title"] = df["title"].fillna("").apply(clean)
    df["text"]  = df["text"].fillna("").apply(clean)

    train_ids = pd.read_csv(SPLITS_DIR / "train_ids.csv")["row_id"].to_numpy()
    train_df  = df.loc[train_ids]
    texts  = (train_df["title"] + " " + train_df["text"]).to_numpy()
    labels = train_df["label"].to_numpy().astype(int)

    nb = BernoulliNaiveBayes(min_df=2, max_features=20000)
    nb.fit(texts, labels)
    print("  Fitting complete.")

    # Save CountVectorizer separately (sklearn — portable pkl)
    vec_path = API_MODEL / "nb_vectorizer.pkl"
    with open(vec_path, "wb") as f:
        pickle.dump(nb.vectorizer, f)
    print(f"  Saved   nb_vectorizer.pkl → {vec_path}")

    # Save learned log-probability arrays as numpy (no class-reference issues)
    params_path = API_MODEL / "nb_params.npz"
    np.savez(
        params_path,
        log_class_ratio=nb.log_class_ratio_,
        log_feature_prob=nb.log_feature_prob_,
        neg_log_feature_prob=nb.neg_log_feature_prob_,
    )
    print(f"  Saved   nb_params.npz → {params_path}")


if __name__ == "__main__":
    print("=" * 60)
    print("Stacking: Exporting model artifacts to API/model/")
    print("=" * 60)

    for label, path in [
        ("best_mlp.pt",    CKPT_DIR / "best_mlp.pt"),
        ("mlp_scaler.pkl", CKPT_DIR / "mlp_scaler.pkl"),
        ("lstm weights",   ARTIFACTS / "models" / "lstm_classifier.pt"),
        ("lstm vocab",     ARTIFACTS / "vocabs"  / "lstm_vocab.json"),
    ]:
        if not path.exists():
            print(f"ERROR: {label} not found at {path}")
            print("       Make sure generate_predictions.py and train.py have been run.")
            sys.exit(1)

    export_lstm()
    export_mlp()
    export_nb()

    print("\n" + "=" * 60)
    print("Done. API/model/ is ready.")
    print("=" * 60)
