# Generated by Claude Code
# ML/stacking/mlp.py
#
# MLP meta-learner for the stacking ensemble.
#
# Architecture:
#   Input (4)  →  Linear(32) → ReLU → Dropout(0.3)
#              →  Linear(16) → ReLU → Dropout(0.3)
#              →  Linear(1)  → Sigmoid
#
# Input features: [gru_prob, lstm_prob, nb_prob, is_political]
# Output:         probability of being fake (scalar in [0, 1])
# Loss:           BCELoss   (sigmoid is inside the model, not the loss)
# Optimiser:      Adam (lr=1e-3)

import torch
import torch.nn as nn


class MLPMetaLearner(nn.Module):
    def __init__(
        self,
        input_size: int = 5,
        hidden1: int = 64,
        hidden2: int = 32,
        dropout: float = 0.05,
    ):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_size, hidden1),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden1, hidden2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden2, 1),
            nn.Sigmoid(),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Parameters
        ----------
        x : FloatTensor of shape (batch, 4)

        Returns
        -------
        FloatTensor of shape (batch,) — probability of fake
        """
        return self.net(x).squeeze(1)
