# Generated by Claude Code
# ML/stacking/train.py
#
# Trains the MLP meta-learner on the stacked base-model predictions.
#
# Usage (from project root):
#   python ML/stacking/train.py
#
# Prerequisites:
#   Run ML/stacking/generate_predictions.py first to create train/val CSVs.
#
# Outputs:
#   ML/stacking/checkpoints/best_mlp.pt  — best model checkpoint (by val AUC-ROC)
#
# Per-epoch log format:
#   Epoch  1/100 | Train Loss 0.4321 | Val Loss 0.3210 | Val Acc 0.9012 | Val F1 0.9034 | Val AUC 0.9512

import sys
from pathlib import Path

SCRIPT_DIR   = Path(__file__).resolve().parent
ML_DIR       = SCRIPT_DIR.parent
PROJECT_ROOT = ML_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT))

import pickle
import numpy as np
import torch
import torch.nn as nn
from sklearn.metrics import f1_score, roc_auc_score

from ML.stacking.data import get_dataloaders
from ML.stacking.mlp  import MLPMetaLearner

# ── hyper-parameters ──────────────────────────────────────────────────────────
MAX_EPOCHS = 100
PATIENCE   = 10
BATCH_SIZE = 64
LR         = 1e-3
THRESHOLD  = 0.5

CHECKPOINT_DIR  = SCRIPT_DIR / "checkpoints"
CHECKPOINT_PATH = CHECKPOINT_DIR / "best_mlp.pt"
DEVICE          = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ── evaluation helper ─────────────────────────────────────────────────────────
def evaluate(model: nn.Module, loader, criterion) -> dict:
    """Run model in eval mode; return loss, accuracy, F1, AUC-ROC."""
    model.eval()
    all_probs, all_true, total_loss = [], [], 0.0

    with torch.no_grad():
        for X_batch, y_batch in loader:
            X_batch = X_batch.to(DEVICE)
            y_batch = y_batch.to(DEVICE)
            probs   = model(X_batch)
            loss    = criterion(probs, y_batch)
            total_loss += loss.item() * len(y_batch)
            all_probs.append(probs.cpu().numpy())
            all_true.append(y_batch.cpu().numpy())

    probs_np = np.concatenate(all_probs)
    true_np  = np.concatenate(all_true)
    preds_np = (probs_np >= THRESHOLD).astype(int)
    n        = len(true_np)

    return {
        "loss": total_loss / n,
        "acc":  (preds_np == true_np.astype(int)).mean(),
        "f1":   f1_score(true_np, preds_np, zero_division=0),
        "auc":  roc_auc_score(true_np, probs_np),
    }


# ── training ──────────────────────────────────────────────────────────────────
def train():
    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

    print("=" * 70)
    print("Stacking Ensemble — MLP Meta-Learner Training")
    print("=" * 70)
    print(f"Device  : {DEVICE}")
    print(f"Epochs  : {MAX_EPOCHS}   Patience: {PATIENCE}   LR: {LR}")
    print()

    print("Loading data …")
    train_loader, val_loader, _, scaler = get_dataloaders(batch_size=BATCH_SIZE)
    print("Data loaded.\n")

    model     = MLPMetaLearner().to(DEVICE)
    criterion = nn.BCELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=LR)

    best_val_f1      = -1.0
    patience_counter = 0
    col_width        = 70

    header = (
        f"{'Epoch':>8} | {'Train Loss':>10} | {'Val Loss':>8} |"
        f" {'Val Acc':>7} | {'Val F1':>6} | {'Val AUC':>7}"
    )
    print(header)
    print("-" * col_width)

    for epoch in range(1, MAX_EPOCHS + 1):
        # ── train one epoch ───────────────────────────────────────────────────
        model.train()
        train_loss_total = 0.0
        n_train          = 0

        for X_batch, y_batch in train_loader:
            X_batch = X_batch.to(DEVICE)
            y_batch = y_batch.to(DEVICE)

            optimizer.zero_grad()
            probs = model(X_batch)
            loss  = criterion(probs, y_batch)
            loss.backward()
            optimizer.step()

            train_loss_total += loss.item() * len(y_batch)
            n_train          += len(y_batch)

        train_loss = train_loss_total / n_train

        # ── validate ──────────────────────────────────────────────────────────
        val_metrics = evaluate(model, val_loader, criterion)

        print(
            f"{epoch:>5}/{MAX_EPOCHS:<3} | {train_loss:>10.4f} | "
            f"{val_metrics['loss']:>8.4f} | {val_metrics['acc']:>7.4f} | "
            f"{val_metrics['f1']:>6.4f} | {val_metrics['auc']:>7.4f}"
        )

        # ── checkpoint & early stopping ───────────────────────────────────────
        if val_metrics["f1"] > best_val_f1:
            best_val_f1      = val_metrics["f1"]
            patience_counter = 0
            torch.save(model.state_dict(), CHECKPOINT_PATH)
            print(f"         ✓ New best Val F1 {best_val_f1:.4f} — checkpoint saved.")
        else:
            patience_counter += 1
            if patience_counter >= PATIENCE:
                print(f"\nEarly stopping triggered after {epoch} epochs (patience={PATIENCE}).")
                break

    print("-" * col_width)
    print(f"\nTraining complete.")
    scaler_path = CHECKPOINT_DIR / "mlp_scaler.pkl"
    with open(scaler_path, "wb") as f:
        pickle.dump(scaler, f)
    print(f"Best Val F1      : {best_val_f1:.4f}")
    print(f"Checkpoint saved : {CHECKPOINT_PATH}")
    print(f"Scaler saved     : {scaler_path}")


if __name__ == "__main__":
    train()
